Initial pull request for clientgen fork to master ptp repo.
facebookincubator/ptp pull request #34
Opened 2021-08-23 15:24 UTC by julianstj1

## Summary

This change implements a client traffic generator that can be used on any hardware that also supports PTP hardware timestamping. It allows for a large amount of clients and can be scaled with more worker threads by editing the json configuration file. This will allow us to test our server implementation and provide a framework for any other stateful client software generation.

## Test Plan
Ran multiple configurations of clientgen with different client IP ranges, ranging from 1000 clients to over 1 million clients. Enabled full print logging to log all the client latencies, client grant counters, and packet counters. Here is a log of running clientgen against ptp4u.

[traffic_gen_log.txt](https://github.com/facebookincubator/ptp/files/7033054/traffic_gen_log.txt)

2021-08-24 14:33 UTC, abulimov requested changes
Can you please remove all the commented out code and extra empty lines? It's hard to review the code otherwise.
Maybe also split massive client.go into multiple files.

And please format all go files with `gofmt`.

2021-08-24 14:33 UTC, abulimov commented on protocol/timestamp.go
> +var Timestamping = unix.SO_TIMESTAMPING_NEW // value 37
It's not 37 (which is the value of `SO_TIMESTAMPING`, it's 0x41, or 65 in decimal

2021-08-24 14:33 UTC, abulimov commented on protocol/protocol.go
> +const HeaderSize = 34 // bytes
bad merge

2021-08-24 14:33 UTC, abulimov commented on protocol/types.go
> +const TlvHeadSize = 4
tlvHeadSize is already there, simply make it exported

2021-08-24 14:33 UTC, abulimov commented on clientgen/README.md
> +
This needs to provide more details, as of now it's unclear what the purpose of this tool is

2021-08-24 17:24 UTC, julianstj1 commented on protocol/timestamp.go
> +var Timestamping = unix.SO_TIMESTAMPING_NEW // value 37
Removed this comment

2021-08-24 17:25 UTC, julianstj1 commented on protocol/protocol.go
> +const HeaderSize = 34 // bytes
Removed duplicate, changed to exposed variable

2021-08-24 17:27 UTC, julianstj1 commented on protocol/types.go
> +const TlvHeadSize = 4
Removed duplicate TlvHeadSize, changed to exported variable

2021-08-24 18:21 UTC, julianstj1 commented on clientgen/README.md
> +
Added quite a bit more detail to README, will fix the formatting as well

2021-08-30 12:02 UTC, leoleovich requested changes
Thanks for the unit tests. It's already much better but still requires some love :)

2021-08-30 12:02 UTC, leoleovich commented on clientgen_lib/io_wkr.go
> +)
Same - order according to the style recommendation:
```
std

external
```

2021-08-30 12:02 UTC, leoleovich commented on clientgen_lib/time_heap.go
> +func (h *timeHeap) Swap(i, j int) {
All public functions must have a comment to generate the go doc

2021-08-31 22:46 UTC, julianstj1 commented on clientgen/main.go
> +	"time"
Yep sorry about this, missed these imports. It's fixed now.

2021-08-31 22:46 UTC, julianstj1 commented on clientgen_lib/counter_processor.go
> +	"time"
Sorry missed doing this again, fixed now.

2021-08-31 22:49 UTC, julianstj1 commented on clientgen/main.go
> +	testConfig := &genlib.ClientGenConfig{}
This is good feedback. I thought about it a while and I think I prefer the configuration file for two reasons:
1. There are a lot of knobs to adjust, so I need or at least strongly want some level of config file. 
2. I like having all the config in one place, so if I want to reproduce someone's test run, I just need the config file. Similar to Ixia or Spirent, where I can load the config and it has everything.

2021-08-31 22:55 UTC, julianstj1 commented on clientgen_lib/io_wkr.go
> +)
Fixed, thanks!

2021-08-31 22:55 UTC, julianstj1 commented on clientgen_lib/time_heap.go
> +func (h *timeHeap) Swap(i, j int) {
Added comments for these, thanks!

2021-08-31 22:56 UTC, julianstj1 commented on clientgen_lib/counter_processor.go
> +		startTime = fastime.Now()
I originally used time.Now() instead, but that seems to have a lot of overhead (it was the dominant item in pprof when I was using it), so that's why I used fastime.

2021-08-31 23:10 UTC, julianstj1 commented on protocol/types.go
> +func TlvHeadSize() int {
Added a comment

2021-08-31 23:11 UTC, julianstj1 commented on protocol/timestamp.go
> +func RecvMsgs(connFd int, rawMsg []byte, sentPkt []byte) (int, int, error) {
Added a comment with some description, thanks for the example!
Removed the oobn int, it wasn't needed.

2021-08-31 23:11 UTC, julianstj1 commented on clientgen_lib/time_heap.go
> +func (h *timeHeap) Less(i, j int) bool {
Added tests for heap operations.

2021-08-31 23:12 UTC, julianstj1 commented on clientgen_lib/perf_meas.go
> +func (p *Profiler) Tick() {
Added unit tests for the perf_meas profiler.

2021-08-31 23:12 UTC, julianstj1 commented on clientgen_lib/perf_meas.go
> +func (p *Profiler) GetLastBusy() float64 {
Added unit tests for the perf_meas profiler.

2021-08-31 23:12 UTC, julianstj1 commented on clientgen_lib/io_wkr.go
> +func start_ioWkr(cfg *ClientGenConfig) {
Renamed

2021-08-31 23:12 UTC, julianstj1 commented on clientgen_lib/client_data.go
> +func IpBetween(from net.IP, to net.IP, test net.IP) bool {
Added unit test for IpBetween

2021-08-31 23:13 UTC, julianstj1 commented on clientgen_lib/client_data.go
> +func NextIP(ip net.IP, step int) net.IP {
Combined NextIP4 and NextIP6 into NextIP, added unit tests for NextIP

2021-08-31 23:13 UTC, julianstj1 commented on clientgen_lib/client_data.go
> +func ipSubtract(a net.IP, b net.IP) (uint64, error) {
Added unit test for ipSubtract

2021-08-31 23:14 UTC, julianstj1 commented on clientgen_lib/requests.go
> +func reqUnicast(clockID ptp.ClockIdentity, duration time.Duration, what ptp.MessageType) *ptp.Signaling {
These functions I actually just copied from simpleclient example. I just edited them to reduce allocations. Do they need to be unit tested?

2021-09-08 15:14 UTC, abulimov commented on clientgen/main.go
> +	cpuprofile := "cpuprofile.prof"
Typically cpuprofile generation is put behind a flag. It's certainly not expected for cli apps to just write to random locations.

2021-09-08 15:35 UTC, abulimov requested changes
Thank you for the updated revision, we are getting closer!

Please remove `clientgen/main` binary file, no binaries should be committed.

I've left line comments, most of them apply to the rest of the similar code.

2021-09-08 15:35 UTC, abulimov commented on clientgen/main.go
> +	configFile := "clientgen_config.json"
Config filename should also be configurable via a flag

2021-09-08 15:35 UTC, abulimov commented on clientgen/main.go
> +	file, err := os.Open(configFile)
Missing `defer file.Close()`.

2021-09-08 15:35 UTC, abulimov commented on clientgen/main.go
> +	genlib "github.com/facebookincubator/ptp/clientgen_lib"
Standard library imports should be separate by empty line from third-party imports.

```
import (
	"os"
	...
	"encoding/json"

	genlib "github.com/facebookincubator/ptp/clientgen_lib"
	...
)
```

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/client.go
> +	"golang.org/x/sync/semaphore"
Again, please separate standard and thrid-party imports with empty line.

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/client.go
> +	if cfg.Debug_print || cfg.Debug_logClient || true {
Go doesn't use snake_case, it uses CamelCase for pretty much everything.

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/client.go
> +	time.Sleep(10 * time.Millisecond)
Sleep is not good for synchronization, please use channels

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/client.go
> +		fmt.Printf("Failed to parse cfg ServerMAC %v\n", err)
Please use either `fmt.Printf` or `log.*` for messages everywhere outside of `main.go`, log gives timestamps and filtering abilities, and mixing both leads to problems with event readability.

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/counter_processor.go
> +			log.Infof("Counter processor done due to err %v", err)
I'd suggest using log levels and use `log.Errorf` for messaging about errors.

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/io_wkr.go
> +						log.Fatalln("pfring ring creation error:", err)
Using `log.Fatal` outside of `main` function is undesirable, as it essentially means `log.Error()` followed by `os.Exit(1)`. When program exits like this, none of `defer` functions will get called.

Please use either return values or channels to return errors.

2021-09-08 15:35 UTC, abulimov commented on clientgen_lib/io_wkr.go
> +									//txTSworker[workerNum].CountIdle()
debug cruft

2021-09-08 15:35 UTC, abulimov commented on protocol/timestamp_test.go
> +	"golang.org/x/sys/unix"
Please revert to original formatting

2021-09-09 03:33 UTC, julianstj1 commented on clientgen/main.go
> +	configFile := "clientgen_config.json"
Added flags for cpuprofile log file and configFile, with cpuprofile being optional.

2021-09-09 03:33 UTC, julianstj1 commented on clientgen/main.go
> +	file, err := os.Open(configFile)
Added , good catch

2021-09-09 03:34 UTC, julianstj1 commented on clientgen/main.go
> +	genlib "github.com/facebookincubator/ptp/clientgen_lib"
Changed this for all files

2021-09-09 03:34 UTC, julianstj1 commented on clientgen_lib/client.go
> +	if cfg.Debug_print || cfg.Debug_logClient || true {
Changed this everywhere I found

2021-09-09 03:35 UTC, julianstj1 commented on clientgen_lib/client.go
> +	time.Sleep(10 * time.Millisecond)
Used atomic counters to keep track of how many goroutines have started instead

2021-09-09 03:35 UTC, julianstj1 commented on clientgen_lib/client.go
> +		fmt.Printf("Failed to parse cfg ServerMAC %v\n", err)
Changed everything to log functions, except counterProcessor prints where I want to control the formatting more precisely.

2021-09-09 03:40 UTC, julianstj1 commented on clientgen_lib/counter_processor.go
> +			log.Infof("Counter processor done due to err %v", err)
Changed error messages to log.Errorf

2021-09-09 03:41 UTC, julianstj1 commented on clientgen_lib/io_wkr.go
> +						log.Fatalln("pfring ring creation error:", err)
Changed away from Fatalln to Errorf and returning on error channel

2021-09-09 03:41 UTC, julianstj1 commented on clientgen_lib/io_wkr.go
> +									//txTSworker[workerNum].CountIdle()
Removed

2021-09-09 03:42 UTC, julianstj1 commented on clientgen_lib/client.go
> +	"golang.org/x/sync/semaphore"
Separated with empty lines

2021-09-09 03:42 UTC, julianstj1 commented on protocol/timestamp_test.go
> +	"golang.org/x/sys/unix"
Reverted back

2021-09-09 03:42 UTC, julianstj1 commented on clientgen/main.go
> +	cpuprofile := "cpuprofile.prof"
Changed it to be a flag argument

2021-09-10 13:26 UTC, abulimov requested changes
@julianstj1 I'm afraid your latest force-push wrote over most the changes from https://github.com/facebookincubator/ptp/commit/8edec5b135c4a7af47510a8eeb091d4d8da9eb3e, please fix this so I can review the update version.

2021-09-10 13:26 UTC, abulimov commented on clientgen/main.go
> +		log.Errorf("Failed to decode config file err %v\n", err)
No need to add `\n` in log statements

2021-09-10 15:47 UTC, julianstj1 commented on clientgen/main.go
> +		log.Errorf("Failed to decode config file err %v\n", err)
Removed these \n in log statements

2021-09-10 16:37 UTC, abulimov requested changes
Please resolve merge conflict in circleci config.

Also it seems like this pull-request is based on relatively old commit of the main branch, can you please rebase it to latest?

2021-09-10 16:37 UTC, abulimov commented on clientgen/main.go
> +	file, err := os.Open(configFile)
still no `defer file.Close()`

2021-09-10 16:37 UTC, abulimov commented on clientgenlib/client.go
> +		//log.Infof("Handle incoming PTP fromTX")
debug cruft

2021-09-10 16:37 UTC, abulimov commented on clientgenlib/client.go
> +			//log.Infof("Signaling udp length %v payload %v", in.udp.Length, len(payload))
ditto

2021-09-10 16:37 UTC, abulimov commented on protocol/timestamp.go
> +	"golang.org/x/sys/unix"
Please return to original formatting

2021-09-10 16:37 UTC, abulimov commented on protocol/types.go
> +func TlvHeadSize() int {
why having a method for this? Simply make `TLVHeadSize` exported, it's `const` anyway.

2021-09-11 01:40 UTC, julianstj1 commented on clientgenlib/client.go
> +		//log.Infof("Handle incoming PTP fromTX")
Good catch, done

2021-09-11 01:40 UTC, julianstj1 commented on clientgenlib/client.go
> +			//log.Infof("Signaling udp length %v payload %v", in.udp.Length, len(payload))
Good catch, done.

2021-09-11 01:48 UTC, julianstj1 commented on clientgen/main.go
> +	file, err := os.Open(configFile)
Sorry missed the one you mentioned, added it now.

2021-09-13 12:54 UTC, leoleovich requested changes
Looking much better!

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/counterProcessor.go
> +
Please remove unnecessary empty lines

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/counterProcessor.go
> +	log.Infof("Total: %v, Max: %v , Min: %v", len(data), max, min)
All of this is should be `%d`

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/counterProcessor.go
> +		return
So what will happen? So let's say we quit and? Will the application continue? Does it need to?

2021-09-13 12:54 UTC, leoleovich commented on clientgen/main.go
> +		pprof.StartCPUProfile(logFile)
I know the CPU profiler was very useful at the beginning. Do you need to keep it or a "regular" profiler like this https://github.com/facebookincubator/ptp/blob/main/ptp4u/main.go#L96 will be enough (it will simplify a lot of code IMHO).

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/client.go
> +	b, _ := ptp.Bytes(payload)
Are you ignoring the error on purpose?

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/client.go
> +	temp := fastime.Now().Add(1000 * time.Millisecond)
time.Second?

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/client.go
> +	temp := fastime.Now().Add(1000 * time.Millisecond)
Also would be nice to know why :D `temp` does not make it easier to read :)

2021-09-13 12:54 UTC, leoleovich commented on clientgenlib/client.go
> +			log.Infof("Got ipv6 %+v", ip6)
Should such thing simply use `log.Debugf`? Seems weird to see `if cfg.DebugPrint` over and over again....

2021-09-14 16:37 UTC, julianstj1 commented on clientgen/main.go
> +  defer file.Close()
Fixed, good catch.

2021-09-14 16:37 UTC, julianstj1 commented on clientgenlib/client.go
> +/*
Moved it under clientgen/clientgenlib so it's not top level.

2021-09-14 16:37 UTC, julianstj1 commented on clientgenlib/client.go
> +		cfg.RunData.rawOutput[i] = make(chan *outPacket, 10000)
Made these constants at the top of client.go

2021-09-14 16:37 UTC, julianstj1 commented on clientgenlib/client.go
> +		startCap := (len(cfg.RunData.clients) / cfg.NumClientRetransmitProcs) + 10
Made this a constant at the top of client.go

2021-09-14 16:38 UTC, julianstj1 commented on clientgenlib/client.go
> +		startCap := (len(cfg.RunData.clients) / cfg.NumClientRestartProcs) + 10
Made this 10 a constant at top of client.go also.

2021-09-14 16:38 UTC, julianstj1 commented on clientgenlib/client.go
> +	cfg.RunData.commonSerializeOp.ComputeChecksums = true
Moved this higher in the initialization code

2021-09-14 16:38 UTC, julianstj1 commented on clientgenlib/client.go
> +	//cfg.RunData.rawOutput = make(chan outPacket, 20000)
Removed, good catch

2021-09-14 16:39 UTC, julianstj1 commented on clientgenlib/counterProcessor.go
> +
I actually just removed this function, so all good now

2021-09-14 16:39 UTC, julianstj1 commented on clientgenlib/counterProcessor.go
> +	log.Infof("Total: %v, Max: %v , Min: %v", len(data), max, min)
Changed to %d

2021-09-14 16:40 UTC, julianstj1 commented on clientgenlib/counterProcessor.go
> +		return
This is a normal case, I use this sometimes actually. There are debug cases where I enable debug printing and I want to just look at the debug messages. If I change the Interval to 0, then the counters don't print periodically. If the counters are periodically printing, it makes it difficult to read the debug messages, so this is intentional.

2021-09-14 16:43 UTC, julianstj1 commented on clientgen/main.go
> +		pprof.StartCPUProfile(logFile)
For now I prefer it as is. It can be changed later if we use this code and want to change this.

2021-09-14 16:44 UTC, julianstj1 commented on clientgenlib/client.go
> +	b, _ := ptp.Bytes(payload)
Changed it to catch the error.

2021-09-14 16:45 UTC, julianstj1 commented on clientgenlib/client.go
> +	temp := fastime.Now().Add(1000 * time.Millisecond)
Actually changed this to a config file item so we can adjust how aggressively the clients try to retransmit.

2021-09-14 16:47 UTC, julianstj1 commented on clientgenlib/client.go
> +			log.Infof("Got ipv6 %+v", ip6)
Changed quite a few of them to Debugf. I prefer to keep printing configurable via the config file so I have greater control over where I want messages to print.

2021-09-14 16:47 UTC, julianstj1 commented on clientgen/main.go
> +		log.Errorf("Failed to open config file %v err %v", configFile, err)
Changed to %s

2021-09-16 13:33 UTC, leoleovich requested changes

2021-09-16 13:33 UTC, leoleovich commented on clientgen/main.go
> +	testConfig := &genlib.ClientGenConfig{}
Its your choice obviously. Setting most of the knobs to default values will likely cut it for you. Having a config file makes it way harder to start using for a new user.

2021-09-16 13:33 UTC, leoleovich commented on clientgen/clientgenlib/timeHeap_test.go
> +func Test_isEmptyAfterSoleElementRemoved(t *testing.T) {
Please don't use "Test_". This is outdated practice and we use TestSomething (no "_") everywhere.

2021-09-16 13:33 UTC, leoleovich commented on clientgen/clientgenlib/perfMeas.go
> +	ctx *context.Context
Yeah, this is a very bad practice. https://pkg.go.dev/context

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:

2021-09-16 13:33 UTC, leoleovich commented on clientgen/clientgenlib/packetProcessor.go
> +	cl, err := getClientFromIP(cfg, icmpv6ns.TargetAddress)
no "getters" please :) Just `clientFromIP`.

2021-09-16 13:33 UTC, leoleovich commented on clientgen/clientgenlib/packetProcessor.go
> +		ipv6.DstIP.IsInterfaceLocalMulticast()) {
You know it's not Python - you can have lines as long as needed :)

2021-09-16 13:33 UTC, leoleovich commented on clientgen/clientgenlib/ioWkr.go
> +					}
Can't timestamp library be used?
https://github.com/facebookincubator/ptp/blob/8d2a7fdd83c72952338d7bafc1e447bb678cd858/protocol/timestamp.go#L112

2021-09-16 13:36 UTC, leoleovich commented
I am looking at the test output:
https://app.circleci.com/pipelines/github/facebookincubator/ptp/291/workflows/9f9dad1c-9623-45a1-a3e8-6d435162a729/jobs/876

It seems like your tests are not actually running. May something to do with the naming :/

2021-09-16 13:44 UTC, leoleovich requested changes

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +
kill

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +
kill

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +
ditto

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +*/
Please remove it.

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +
ditto

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +		}
Can't you move all of this inside of 799? Then you can get rid of isIP4/isIP6 ?

2021-09-16 13:44 UTC, leoleovich commented on clientgen/clientgenlib/client.go
> +
kill

2021-09-16 14:12 UTC, abulimov commented
@julianstj1 I know the reason unittests and linter don't work for `clientgen` - it's because of submodules.

I don't see why we need them in a first place, so can you please just remove `clientgen/go.mod`, `clientgen/go.sum` and `clientgen/clientgenlib/go.mod`, `clientgen/clientgenlib/go.sum`, then run `go mod tidy` in the top level directory.

This will make *clientgen* a part of `https://github.com/facebookincubator/ptp` module, and `go test github.com/facebookincubator/ptp/...` will finally be able to pick up your tests, and same will apply to linters and formatters.

2021-09-17 11:28 UTC, abulimov commented
Forgot to mention that `clientgen/go.mod` should say `module github.com/facebookincubator/ptp/clientgen`, not `module main`.

2021-09-17 17:35 UTC, julianstj1 commented
Closing pull request, checked in into other github location. Thanks for all your help with improving the code, learned a lot about golang and particularly unit tests I wouldn't have otherwise.

2021-09-17 17:35 UTC, closed without merging